services:
  pulsar:
    container_name: pulsar
    image: apachepulsar/pulsar:latest
    command: bin/pulsar standalone
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    ports:
      - 6650:6650
      - 8080:8080
    restart: unless-stopped